---
title: "Figure"
author: "Melanie"
date: "7/13/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r libraries}
library(monocle3)
library(CoGAPS)
library(ggplot2)
library(dplyr)
library('ComplexHeatmap')
library(forcats)
library(knitr)
sessionInfo()
```

```{r loadData}
## Load the cds objects
load("Results/cellCycle_EJFPsuedotimeResults2Mar2020.Rda")
## Load the CoGAPS 20 Pattern Result
cogapsRes <- readRDS("Results/gwCogapsRes/emtGwCogaps_20.rds")
## Load the pathways results for the emt pathwyay
emtPatterns <- read.csv(file = "Results/msigdb/emtPatterns.csv", header = TRUE)
## Load the pattern markers
patternMarkerResults <- read.csv(file = "Results/patternMarkers_emtGwCogaps_20.csv")
## Load the EMT genes
emtGenes <- read.csv("Results/geneList.csv", header = FALSE)
```

## Panel A : Cell cycle
```{r}
## Plot the cell cycle
plot_cells(cdsNorm, color_cells_by = "phase", label_cell_groups = FALSE) +
    ggtitle("Cell Cycle Phase")
```


## Panel B : Violin plots of Cdh1 / Vim by cell cycle state
```{r violinPlot}
## Violin plot
## Subset to Vim and CDH1
cdsSubset <- cdsNorm[rowData(cdsNorm)$gene_short_name %in% c("Vim", "Cdh1"), ]
plot_genes_violin(cdsSubset, group_cells_by = "phase", ncol = 2)
```

## Panel C : Barplot of -10*log10(p values) for the hallmark EMT pathway
```{r}
## Make barplot for the hallmark emt pathway----
## Read in the emt pathway tables
emtPatterns <- read.csv("Results/msigdb/HighPValueResults/emtResults.csv")
## Add the column with the updated p value
emtPatterns$'-10*log10(adj.p.value)' <- (-10)*log10(emtPatterns$FDR.q.value)


## Make the barplot

emtPatterns %>% 
    ## Reorders the barplots
    mutate(Pattern=fct_reorder(Pattern, desc(p.value) )) %>%
    ggplot(aes_string(y = "-10*log10(p.value)", x = "Pattern", fill = "Pattern")) +
    ## Specifies barplot
    geom_col() +
    ## Flips the coordinates
    coord_flip() +
    ## Makes the background white
    theme_minimal() +
    ## Add title
    ggtitle("Hallmark EMT Pathway") +
    ## This creates the dotted line at .05 value 
    geom_hline(yintercept=c(13.0103), linetype="dotted") + # Add veritcle line to show significances
    ## Adds the q values
    geom_text(aes(label=FDR.q.value), hjust = -.04) +
    ## Removes legend
    theme(legend.position = "none") +
    ## specifies limits 
    ylim(0, 450)

```


## Panel D : Heatmap with * added to the heatmap if it's a pattern marker gene 
```{r, fig.height=6}
## Heatmap of the amplitude matrix ----
## Extract the amplitude matrix while dropping the cell line patterns
amplitude <- cogapsRes@featureLoadings[rownames(cogapsRes@featureLoadings) %in% emtGenes$V1, 
    !colnames(cogapsRes@featureLoadings) %in%c("Pattern_2", "Pattern_13")]

## Scale and center the data
scaledmat<- t(apply(amplitude, 1, scale))

## Reassign the column names
colnames(scaledmat) <- colnames(amplitude)

## Add * if the gene is a pattern marker for 
## initalize an empty matrix
small_mat <- matrix("", nrow = 33, ncol= 17)
## Add row and column names to matrix
rownames(small_mat) <- rownames(scaledmat)
colnames(small_mat) <- colnames(scaledmat)

## Add * if the gene is pattern marker
for (i in rownames(small_mat)){
    for(j in colnames(patternMarkerResults)){
        if( paste0(i) %in% patternMarkerResults[,paste0(j)]) {
            small_mat[paste(i), paste0(j)] <- "*"
        }
    }
}
## Create the heatmap
Heatmap(scaledmat, name = "Amplitude",cluster_columns = TRUE,
        show_row_dend = FALSE, 
        show_column_dend = FALSE,
        column_title = "Amplitude Heatmap of EMT Genes (nPattern = 20)",
        cell_fun = function(j, i, x, y, width, height, fill) {
        grid.text(sprintf(small_mat[i, j]), x, y, gp = gpar(fontsize = 10))
})


```


## Panel E : UMAPS colored by pattern weights for patterns 5, 8, and 14 
```{r}
## Create the pattern umaps ----
cdsNorm@colData <- cbind(colData(cdsNorm), cogapsRes@sampleFactors[colnames(cdsNorm), ])

## Pattern 5
plot_cells(cdsNorm, color_cells_by = "Pattern_5", label_cell_groups = FALSE)

## Pattern 8
plot_cells(cdsNorm, color_cells_by = "Pattern_8", label_cell_groups = FALSE)

## Pattern 12
plot_cells(cdsNorm, color_cells_by = "Pattern_12", label_cell_groups = FALSE) 

## Pattern 14
plot_cells(cdsNorm, color_cells_by = "Pattern_14", label_cell_groups = FALSE)
```


## Panel F : Show percentage of cells in each pattern
```{r}
## Subset the cogaps results to the specific patterns
## Duplicate the result to manipulate 
filteredCogaps <- cogapsRes
## Eliminate the cell line patterns
filteredCogaps@sampleFactors <- filteredCogaps@sampleFactors[, !colnames(filteredCogaps@sampleFactors) %in%c("Pattern_2", "Pattern_13")]
## Run the pattern marker statistic on the cells 
cellPatternMarker <- patternMarkers(filteredCogaps, axis = 2)
## Add the pattern to the cell marker result
for(i in 1:length(cellPatternMarker$PatternMarkers)){
    ## Concert to a df
    cellPatternMarker$PatternMarkers[[i]] <- as.data.frame(cellPatternMarker$PatternMarkers[[i]])
    ## create column name
    colnames(cellPatternMarker$PatternMarkers[[i]]) <- "CellID"
    cellPatternMarker$PatternMarkers[[i]]$Pattern <- names(cellPatternMarker$PatternMarkers[i])
}
## Combined the tables
cellPatternMarkerDataFrame <- do.call("rbind", cellPatternMarker$PatternMarkers)
## Update rownames
rownames(cellPatternMarkerDataFrame) <- cellPatternMarkerDataFrame$CellID

## Add the pattern assignment to the cds
colData(cdsNorm)$AssignedPattern <- cellPatternMarkerDataFrame[colnames(cdsNorm), "Pattern"]
## Plot the data
plot_cells(cdsNorm, color_cells_by = "AssignedPattern", label_cell_groups = FALSE)
## Show pattern 5, 8, and 12 only
plot_cells(cdsNorm, color_cells_by = "AssignedPattern", label_cell_groups = FALSE) +
    scale_color_manual(values = c("gray80","gray80","gray80","black","#2297E6",
                                  "gray80","gray80","gray80","gray80","gray80",
                                  "gray80","gray80","#F5C710","gray80","gray80",
                                  "#CD0BBC","gray80"))
# Generate a table which counts cells assigned to each pattern
countsTable <- table(colData(cdsNorm)$AssignedPattern)
## make a proportion table with the counts table
propTable <- as.data.frame(prop.table(countsTable))
## round the proportions
propTable$Freq <- round(propTable$Freq, digits = 4)
## Merge the two tables
combinedTable <- merge(as.data.frame(countsTable), propTable, by = "Var1")
## Rename columns
colnames(combinedTable) <- c("Pattern", "Number of Cells in Pattern", "Proportion of Cells in Pattern")
## Create table
kable(combinedTable)

```

```{r}
# ## Make umaps for the gene's in gene list
# pdf("Results/emtGeneUmaps.pdf")
# for (i in 1:length(emtGenes$V1)){
#     print(plot_cells(cdsNorm, genes = paste0(emtGenes$V1[i])))
# }
# dev.off()

```
## Panel G : UMAP Showing Vim and Cdh1 positive/negative cells
```{r}
## Subset the cds p data to Vim and Cdh1
countsDataFrame <- as.data.frame(as.matrix(counts(cdsNorm)))
countsSubset <- t(countsDataFrame[rownames(countsDataFrame) %in% c("Vim", "Cdh1"), ])
## Classify by expression of the genes of interst
classifiedCounts <- as.data.frame(countsSubset) %>%
    mutate(classification = ifelse(Vim > 0 & Cdh1 > 0, "Double Positive",
                                   ifelse(Vim > 0 & Cdh1 == 0, "Vim Positive",
                                   ifelse(Vim == 0 & Cdh1 > 0, "Cdh1 Positive",
                                   "Double Negative"))))
## Add the classification to the cds
colData(cdsNorm)$Classification <- classifiedCounts[colnames(cdsNorm), "classification"]
## Plot the classification
plot_cells(cdsNorm, color_cells_by = "Classification", label_cell_groups = FALSE)
```

