---
title: "CoGAPS Visuals"
author: "Melanie and Joe"
date: "8/2/2021"
output: html_document
---



```{r libraries , message = FALSE, warning = FALSE}
library(CoGAPS)
library('ComplexHeatmap')
```



```{r loadData}
## Load the CoGAPS result
gwCogapsRes <- readRDS("/16_emtMatmatrigel_10.rds")
## Load the EMT genes
emtGenes <- read.csv("/geneList.csv", header = FALSE)
```

```{r patternMarkerRank}
## Calculate the pattern marker statistics ----
## Duplicate the result to manipulate 
filteredCogaps <- gwCogapsRes

## Run pattern marker function
#patternMarkerResults <- patternMarkers(filteredCogaps)
patternMarkerResults <- read.csv(file = "/patternMarkers_emtGwCogapsMatrigel_10.csv")


## Extract the rank results for the EMT genes
emtGeneRanks <- patternMarkerResults$PatternMarkerRanks[rownames(patternMarkerResults$PatternMarkerRanks) %in% emtGenes$V1, ]

## Save the csv
write.csv(emtGeneRanks, file = "emtGeneRanks.csv")
```


```{r,amplitudeHeatmap}
## Heatmap of the amplitude matrix ----
## Extract the amplitude matrix while dropping the cell line patterns
amplitude <- gwCogapsRes@featureLoadings[rownames(gwCogapsRes@featureLoadings) %in% emtGenes$V1, 
    colnames(gwCogapsRes@featureLoadings)]

## Scale and center the data
scaledmat<- t(apply(amplitude, 1, scale))

## Reassign the column names
colnames(scaledmat) <- colnames(amplitude)

## Add * if the gene is a pattern marker for 
## initalize an empty matrix
small_mat <- matrix("", nrow = nrow(scaledmat), ncol= ncol(scaledmat))

## Add row andcolumn names to matrix
rownames(small_mat) <- rownames(scaledmat)
colnames(small_mat) <- colnames(scaledmat)

## Add * if the gene is pattern marker
for (i in rownames(small_mat)){
    for(j in colnames(small_mat)){
      #if (i %in% patternMarkerResults[,j]) { 
      if( paste0(i) %in% patternMarkerResults[,paste0(j)]) {
            small_mat[paste(i), paste0(j)] <- "*"
        }
    }
}


## Create the heatmap
pdf(file = "/P10_Heatmap.pdf")

Heatmap(scaledmat, name = "Amplitude",cluster_columns = TRUE,
        show_row_dend = FALSE, 
        show_column_dend = FALSE,
        row_names_side = "left",
        column_names_side = "bottom",
        column_names_rot = 45,
        column_names_gp = gpar(fontsize=10),
        column_title = "Amplitude Heatmap of EMT Genes (nPattern = 10)",
        cell_fun = function(j, i, x, y, width, height, fill) {
         grid.text(sprintf(small_mat[i, j]), x, y, gp = gpar(fontsize = 10))
})
dev.off()
```

##This code has been repeated using P10,P12,P14,P16 data by substituting the file names. 

